export enum ButtonAlias {
  view = 'view',
  add = 'add',
  edit = 'edit',
  delete = 'delete',
  authorized = 'authorized',
  history = 'history',
  resetPassword = 'resetPassword',
  lock = 'lock',
  unlock = 'unlock',
  deleteAll = 'deleteAll',
  assignment = 'assignment',
  reply = 'reply',
  approval = 'approval',
  export = 'export',
  import = 'import',
}
